name: Power-Automate-Desktop-Release

on:
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Github Release
      uses: elgohr/Github-Release-Action@v5
      with:
        title: Test
        workdir: .
