name: Power-Automate-Desktop-Release
on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Github Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Test
