name: Power-Automate-Desktop-Release

on:
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Power Automate for desktop
      run: |
        Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=2164365 -OutFile Setup.Microsoft.PowerAutomate.exe
        .\Setup.Microsoft.PowerAutomate.exe -Install -AcceptEULA -Silent
        Start-Sleep -Seconds 10
        $processName = "Setup.Microsoft.PowerAutomate"
        do {
          Write-Host "Waiting for process to exit..."
          Start-Sleep -Seconds 10
        } while (Get-Process -Name $processName -ErrorAction SilentlyContinue)
